### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by jdolitsky** [gebogebogebo/ctap-hid-fido2#3]
On Linux, receiving `Failed to open device`.

Is there any plan to add Linux desktop support?

**Comment by gebogebogebo** [comment]
Sorry, Linux is not yet supported. I'm thinking of starting to support Linux in a little while.

**Comment by pmengelbert** [comment]
@gebogebogebo I'm willing to help with Linux support. Do you have an idea of where to start? I'm noticing that while the libusb hidapi can detect my device, it discards it because the usage_page attribute is initialized to 0x0000 instead of 0xf1d0. Setting it manually in the debugger lets it pass the check, but the call to `read` causes the program to hang indefinitely. I'm pretty new to working with hardware in Rust, so if you can point me in the right direction it would be much appreciated

**Comment by gebogebogebo** [comment]
@pmengelbert 
Thank you!
In this crate I use the crate named `hidapi` for access to HID.
The reason why it doesn't work on Linux seems to be that `hidapi` is not supported on Linux.
In order to support Linux, you need to use other crates than `hidapi` or implement it by yourself.
The `ctap_hmac` is compatible with Linux, so this may be helpful.

**Comment by gebogebogebo** [comment]
Developed by the **pi** branch.
I have confirmed that it works fine on the Raspberry Pi.
It might work on Linux as well.

**Comment by nickray** [comment]
hidapi works fine on Linux :+1:

**Comment by gebogebogebo** [comment]
@nickray 
Thanks!
